/**
 * Writes docs/research/spells-report.md (SPEC §32 R2, §33.2 step 7): per spell, how each structured field
 * was obtained, what was missing and how it was resolved, every prose-vs-Foundry disagreement, every
 * cross-check disagreement with Open5e / 5e-bits, and the list of spells needing manual review.
 */
import type { Spell } from "@gloam/shared/schemas";
import type { Sources } from "./fetch-srd.ts";
import { EXPECTED_PER_LEVEL, FOUNDRY, SRD_PDF } from "./lib/pins.ts";
import type { MergedSpell } from "./merge.ts";
import { describeArea } from "./merge.ts";
import type { HyphenDecision } from "./parse-srd-pdf.ts";
import type { CrossCheckDisagreement } from "./verify.ts";

export interface ReportInput {
  spells: Spell[];
  merged: Map<string, MergedSpell>;
  crossCheck: { disagreements: CrossCheckDisagreement[]; missing: string[]; observations: string[] };
  sources: Sources;
  hyphenation: HyphenDecision[];
  parserWarnings: string[];
  droppedFoundry: string[];
  overlayFiles: { file: string; entries: number }[];
  schemaChanges: string[];
  policies: string[];
  higherLevelCount: number;
  cantripUpgradeCount: number;
  pipelineVersion: string;
}

const esc = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");

function levelLabel(l: number): string {
  return l === 0 ? "cantrip" : `level ${l}`;
}

export function renderReport(r: ReportInput): string {
  const lines: string[] = [];
  const out = (s = "") => lines.push(s);
  const counts = Array.from({ length: 10 }, (_, l) => r.spells.filter((s) => s.level === l).length);
  const review = r.spells.filter((s) => (r.merged.get(s.id)?.review.length ?? 0) > 0);
  const xcBySpell = new Map<string, CrossCheckDisagreement[]>();
  for (const d of r.crossCheck.disagreements) {
    const list = xcBySpell.get(d.id) ?? [];
    list.push(d);
    xcBySpell.set(d.id, list);
  }

  out("# SRD 5.2.1 spell data — pipeline report");
  out();
  out(
    `Generated by \`pnpm content:build\` (pipeline ${r.pipelineVersion}). Do not edit by hand; change the pipeline or the overlays in \`packages/content/overlays/\` and rebuild.`,
  );
  out();
  out("## Summary");
  out();
  out(`- **Spells:** ${r.spells.length} (expected 339).`);
  out(`- **Per level (cantrip → 9):** ${counts.join(" / ")} (expected ${EXPECTED_PER_LEVEL.join(" / ")}).`);
  out(
    `- **"Using a Higher-Level Spell Slot" paragraphs:** ${r.higherLevelCount}; **"Cantrip Upgrade" paragraphs:** ${r.cantripUpgradeCount}.`,
  );
  out(`- **Spells needing manual review:** ${review.length} (listed below with reasons).`);
  out(
    `- **Cross-check disagreements:** ${r.crossCheck.disagreements.length} (Open5e and 5e-bits; informational — the PDF wins).`,
  );
  out(
    `- **Foundry files dropped (not in the SRD 5.2.1 spell list):** ${r.droppedFoundry.join(", ") || "none"}.`,
  );
  out();
  out("### Sources");
  out();
  out(`| Source | Pin | Verified |`);
  out(`| --- | --- | --- |`);
  out(
    `| SRD 5.2.1 PDF | ${SRD_PDF.url} | SHA-256 \`${r.sources.pdf.sha256}\`, ${r.sources.pdf.bytes} bytes, ${SRD_PDF.pages} pages |`,
  );
  out(
    `| Foundry dnd5e | ${FOUNDRY.tag} @ \`${r.sources.foundry.commit}\` (${FOUNDRY.spellsPath}) | \`git rev-parse HEAD\` = pin; tag → commit ${r.sources.foundry.tagVerified === true ? "verified" : "not re-checked (cached)"}; tree \`${r.sources.foundry.spellsTree}\` |`,
  );
  for (const src of [r.sources.open5e, r.sources.fiveEBits]) {
    for (const [name, f] of Object.entries(src.files)) {
      out(
        `| ${src.owner}/${src.repo} ${name} | ${src.branch} → \`${src.commit}\` (${f.path}) | SHA-256 \`${f.sha256}\` (cross-check only) |`,
      );
    }
  }
  out();
  out("### Schema changes (additive, optional; `packages/shared/src/schemas/spell.ts`)");
  out();
  for (const c of r.schemaChanges) out(`- ${c}`);
  out();
  out("### Modelling policies");
  out();
  for (const p of r.policies) out(`- ${p}`);
  out();
  out("### Overlays applied");
  out();
  for (const f of r.overlayFiles) out(`- \`overlays/${f.file}\`: ${f.entries} spells`);
  out();
  out("### How to read this report");
  out();
  out(
    "Each structured field records its origin in the spell's `provenance` map: `pdf` (header/text), `foundry` (Foundry dnd5e item data), `prose:<pattern>` (a regular expression over the PDF text), `overlay:<file>` (hand-authored from the PDF, page cited in the overlay), `derived:<rule>` (computed from other fields), or a `+` combination when two sources agree. Notes per spell use these kinds:",
  );
  out();
  out("- **missing** — the preferred source lacked the field; the note says what filled it.");
  out("- **resolved** — a gap or conflict settled by prose or an overlay.");
  out("- **disagreement** — prose (PDF) and Foundry differ; the PDF prose or an overlay wins.");
  out("- **info** — something noteworthy that needs no action (e.g. secondary damage kept in text only).");
  out();

  // Structured coverage
  const noArea = r.spells.filter((s) => !s.area);
  const noSave = r.spells.filter((s) => /saving throw/.test(s.text) && !s.save);
  const noDamage = r.spells.filter(
    (s) => /\d+d\d+ \w+ damage/.test(s.text) && !(s.damage && s.damage.length > 0),
  );
  out("### Coverage of structured fields");
  out();
  out(`| Field | Spells with it |`);
  out(`| --- | --- |`);
  const has = (p: (s: Spell) => boolean) => r.spells.filter(p).length;
  out(`| area | ${has((s) => Boolean(s.area))} |`);
  out(`| save | ${has((s) => Boolean(s.save))} |`);
  out(`| attack | ${has((s) => Boolean(s.attack))} |`);
  out(`| damage | ${has((s) => (s.damage?.length ?? 0) > 0)} |`);
  out(`| healing | ${has((s) => Boolean(s.healing))} |`);
  out(`| conditions | ${has((s) => (s.conditions?.length ?? 0) > 0)} |`);
  out(`| effect (persistent template) | ${has((s) => Boolean(s.effect))} |`);
  out(`| light | ${has((s) => Boolean(s.light))} |`);
  out(`| obscurement | ${has((s) => Boolean(s.obscurement))} |`);
  out();
  out(
    `Spells whose text mentions a saving throw but have no structured \`save\` (the save is conditional, optional or the caster's own; the text carries it): ${noSave.map((s) => s.name).join(", ") || "none"}.`,
  );
  out();
  out(
    `Spells whose text has "NdM <type> damage" but no structured \`damage\`: ${noDamage.map((s) => s.name).join(", ") || "none"}.`,
  );
  out();
  out(`Spells without an \`area\` (targeted, self or no board template): ${noArea.length}.`);
  out();

  out("## Spells needing manual review");
  out();
  out(
    "Every prose-vs-Foundry conflict found by the build is resolved (by the PDF or a PDF-quoting overlay) and listed per spell below. What remains here are **judgment calls**: places where the data has to model something the SRD states in words the schema can't hold exactly (flat shapes, one-of-several wall layouts, delayed or situational damage kept in the text, maximum-HP boosts). A rules reviewer should confirm each; if one is wrong, fix the overlay and rebuild. Unresolved conflicts, if any appear in a future build, are listed here too.",
  );
  out();
  if (review.length === 0) out("None.");
  else {
    out("| Spell | Level | Page | Reasons |");
    out("| --- | --- | --- | --- |");
    for (const s of review) {
      out(
        `| ${esc(s.name)} | ${s.level} | ${s.source.page} | ${esc(r.merged.get(s.id)!.review.join("; "))} |`,
      );
    }
  }
  out();

  out("## Per-spell details");
  out();
  for (let level = 0; level <= 9; level++) {
    out(`### ${level === 0 ? "Cantrips" : `Level ${level}`}`);
    out();
    for (const s of r.spells.filter((x) => x.level === level)) {
      const m = r.merged.get(s.id)!;
      out(`#### ${s.name} (\`${s.id}\`, ${levelLabel(s.level)}, p. ${s.source.page})`);
      out();
      const summary: string[] = [];
      summary.push(`area: ${describeArea(s.area)}`);
      if (s.save) summary.push(`save: ${s.save.ability} (${s.save.onSuccess})`);
      if (s.attack) summary.push(`attack: ${s.attack.kind}`);
      if (s.damage?.length) {
        summary.push(
          `damage: ${s.damage
            .map((d) => {
              const t = d.typeOptions ? d.typeOptions.join("/") : d.type;
              const sc =
                d.scaling?.mode === "slot"
                  ? ` +${d.scaling.perLevel}/slot`
                  : d.scaling?.mode === "cantrip"
                    ? ` (${Object.values(d.scaling.atLevels).join("/")})`
                    : "";
              return `${d.formula} ${t}${sc}`;
            })
            .join(", ")}`,
        );
      }
      if (s.healing)
        summary.push(
          `healing: ${s.healing.formula}${s.healing.scaling?.mode === "slot" ? ` +${s.healing.scaling.perLevel}/slot` : ""}`,
        );
      if (s.conditions?.length) summary.push(`conditions: ${s.conditions.map((c) => c.id).join(", ")}`);
      if (s.light) summary.push(`light: ${s.light.bright}/${s.light.dim}`);
      if (s.obscurement) summary.push(`obscurement: ${s.obscurement}`);
      if (s.effect) summary.push("effect template");
      summary.push(`vfx: ${s.vfx}`);
      out(`- ${summary.join(" · ")}`);
      const prov = s.provenance ?? {};
      const provKeys = Object.keys(prov).filter((k) => prov[k] !== "pdf");
      if (provKeys.length > 0) out(`- provenance: ${provKeys.map((k) => `${k} ← ${prov[k]}`).join("; ")}`);
      for (const n of m.notes) out(`- **${n.kind}** (${n.field}): ${n.message}`);
      for (const d of xcBySpell.get(s.id) ?? []) {
        out(`- **cross-check ${d.source}** (${d.field}): ours \`${d.ours}\` vs theirs \`${d.theirs}\``);
      }
      if (m.review.length > 0) out(`- **manual review:** ${m.review.join("; ")}`);
      out();
    }
  }

  out("## Cross-check coverage");
  out();
  if (r.crossCheck.missing.length === 0)
    out("Every PDF spell is present in Open5e and 5e-bits, and neither lists extra spells.");
  else for (const m of r.crossCheck.missing) out(`- ${m}`);
  out();
  const byField = new Map<string, number>();
  for (const d of r.crossCheck.disagreements) {
    const k = `${d.source} ${d.field.replace(/@.*/, "@slot")}`;
    byField.set(k, (byField.get(k) ?? 0) + 1);
  }
  out(
    "Systematic differences in the cross-check sources (checked against their data; they explain most of the counts below and are not errors in this pack):",
  );
  out();
  for (const o of r.crossCheck.observations) out(`- ${o}`);
  out();
  out("| Source and field | Disagreements |");
  out("| --- | --- |");
  for (const [k, v] of [...byField.entries()].sort()) out(`| ${k} | ${v} |`);
  out();

  out("## Text extraction notes");
  out();
  out("### Parser warnings");
  out();
  if (r.parserWarnings.length === 0) out("None.");
  for (const w of r.parserWarnings) out(`- ${w}`);
  out();
  out("### Line-break hyphens not settled by the PDF's own vocabulary");
  out();
  out(
    "Most hyphenated line breaks are resolved from word forms that occur unbroken elsewhere in the PDF. The breaks below were decided by rule or by the reviewed exceptions in `overlays/hyphenation.json`:",
  );
  out();
  out("| Spell | Break | Result | Rule |");
  out("| --- | --- | --- | --- |");
  for (const h of r.hyphenation.filter(
    (x) => !x.reason.startsWith("dictionary") && x.reason !== "non-alpha",
  )) {
    out(`| ${esc(h.spell)} | ${h.left}- / ${h.right} | ${h.result} | ${h.reason} |`);
  }
  out();
  return `${lines.join("\n")}\n`;
}
