import { readFileSync } from "node:fs";
import { APP_VERSION } from "@gloam/shared";
import type { ServerContext } from "../context.ts";

/**
 * The SRD 5.2.1 attribution, verbatim (SPEC Appendix I — required, word for word; AC-ADM-05). The content pack's own
 * copy must match it (a test compares them).
 */
export const SRD_ATTRIBUTION =
  'This work includes material from the System Reference Document 5.2.1 ("SRD 5.2.1") by Wizards of the Coast LLC, available at https://www.dndbeyond.com/srd. The SRD 5.2.1 is licensed under the Creative Commons Attribution 4.0 International License, available at https://creativecommons.org/licenses/by/4.0/legalcode.';

interface Licences {
  packages: { name: string; version: string; license: string; author?: string; homepage?: string }[];
  fonts: { family: string; license: string; text: string }[];
  vendored: { name: string; version: string; license: string; author?: string; homepage?: string }[];
}

let licences: Licences | null = null;
/** The third-party licences (generated by tools/gen-licences.mjs from the installed packages). */
function loadLicences(): Licences {
  licences ??= JSON.parse(readFileSync(new URL("./licences.json", import.meta.url), "utf8")) as Licences;
  return licences;
}

/**
 * About & Credits (SPEC §8.20, Appendix I): the version, the SRD attribution verbatim, what else the rules content
 * came from, the trademark note, and the licences of the bundled fonts and libraries.
 */
export function aboutGloam(ctx: ServerContext) {
  const l = loadLicences();
  return {
    version: APP_VERSION,
    node: process.version,
    srd: {
      attribution: SRD_ATTRIBUTION,
      pack: ctx.content.id,
      spells: ctx.content.spells.length,
      // The pack's own statement, checked against the verbatim one.
      matches: ctx.content.attribution.trim() === SRD_ATTRIBUTION,
    },
    sources: [
      {
        name: "Foundry VTT dnd5e system",
        note: "Used at build time only, as a structured source for SRD mechanics (area templates, saves, damage, attack types).",
        license: "MIT (code), CC-BY-4.0 (SRD content)",
        homepage: "https://github.com/foundryvtt/dnd5e",
      },
      {
        name: "Open5e and 5e-bits SRD data",
        note: "Used at build time only to cross-check header fields, saves and per-slot dice; nothing copied into the pack.",
        license: "CC-BY-4.0 / MIT",
        homepage: "https://open5e.com",
      },
    ],
    // (Appendix I: beyond the attribution, only "compatible with fifth edition" may be said — no other mention.)
    trademarks:
      "Gloam is compatible with fifth edition. The Creative Commons licence covers the SRD's text; it grants no rights in any trademark.",
    fonts: l.fonts,
    packages: l.packages,
    vendored: l.vendored,
  };
}
