/**
 * The dice as solids (SPEC §18.4): each die's vertices and faces, the markers that say which way is "up" (a face's
 * outward normal; for the d4 the vertex read at the top), the value each marker shows, and the die's rotation
 * symmetry group. Landing on the server's number: the physics body lands with some marker up; the group holds a
 * rotation S taking the wanted marker to the landed one, and the visible mesh is drawn at `q_body · S` — the same
 * solid in the same place (S is a symmetry), showing the wanted number (the group acts transitively on the markers,
 * so S always exists).
 */
import { Quaternion, Vector3 } from "three";

export type DieKind = "d4" | "d6" | "d8" | "d10" | "d12" | "d20";

export interface Solid {
  kind: DieKind;
  /** Vertices, scaled so the die is SIZE across (its circumdiameter). */
  vertices: Vector3[];
  /** Faces as vertex indices, counter-clockwise seen from outside. */
  faces: number[][];
  /** Each face's outward unit normal. */
  normals: Vector3[];
  /** Unit directions whose "most up" one gives the result: face normals, or the d4's vertices. */
  markers: Vector3[];
  /** The value each marker shows. */
  labels: number[];
  /** The rotation symmetry group (unit quaternions, one per rotation). */
  group: Quaternion[];
}

/** A die's size across (cm; 1 unit = 1 cm in the dice world, §18.4). */
export const SIZE = 1.6;

const PHI = (1 + Math.sqrt(5)) / 2;
const UP = new Vector3(0, 1, 0);

function v(x: number, y: number, z: number): Vector3 {
  return new Vector3(x, y, z);
}

/** Outward normal of a planar face (its first three corners), oriented away from the centre. */
function faceNormal(vs: Vector3[], f: number[]): Vector3 {
  const a = vs[f[0] as number] as Vector3;
  const b = vs[f[1] as number] as Vector3;
  const c = vs[f[2] as number] as Vector3;
  const n = new Vector3().subVectors(b, a).cross(new Vector3().subVectors(c, a)).normalize();
  const centroid = new Vector3();
  for (const i of f) centroid.add(vs[i] as Vector3);
  if (n.dot(centroid) < 0) n.negate();
  return n;
}

/** Faces wound counter-clockwise seen from outside. */
function orient(vs: Vector3[], faces: number[][]): number[][] {
  return faces.map((f) => {
    const n = faceNormal(vs, f);
    const a = vs[f[0] as number] as Vector3;
    const b = vs[f[1] as number] as Vector3;
    const c = vs[f[2] as number] as Vector3;
    const w = new Vector3().subVectors(b, a).cross(new Vector3().subVectors(c, a));
    return w.dot(n) >= 0 ? f : [...f].reverse();
  });
}

function scaled(vs: Vector3[]): Vector3[] {
  const r = Math.max(...vs.map((p) => p.length()));
  return vs.map((p) => p.clone().multiplyScalar(SIZE / 2 / r));
}

/** A rotation by `deg` about an axis. */
function rot(axis: Vector3, deg: number): Quaternion {
  return new Quaternion().setFromAxisAngle(axis.clone().normalize(), (deg * Math.PI) / 180);
}

/** q and −q are one rotation: a canonical sign for comparing. */
function canonical(q: Quaternion): Quaternion {
  const c = q.clone().normalize();
  const s = [c.w, c.x, c.y, c.z].find((x) => Math.abs(x) > 1e-9) ?? 1;
  if (s < 0) c.set(-c.x, -c.y, -c.z, -c.w);
  return c;
}

/** The group generated by some rotations: every product, until nothing new appears. */
export function closeGroup(generators: Quaternion[]): Quaternion[] {
  const out: Quaternion[] = [new Quaternion()];
  const same = (a: Quaternion, b: Quaternion) => Math.abs(a.dot(b)) > 1 - 1e-9;
  for (let i = 0; i < out.length; i++) {
    for (const g of generators) {
      const p = canonical(g.clone().multiply(out[i] as Quaternion));
      if (!out.some((q) => same(q, p))) out.push(p);
      if (out.length > 200) throw new Error("not a finite rotation group");
    }
  }
  return out;
}

/** Labels for markers that come in opposite pairs, opposite values summing to n + 1 (as on real dice). */
function oppositeLabels(markers: Vector3[]): number[] {
  const n = markers.length;
  const labels = new Array<number>(n).fill(0);
  let next = 1;
  for (let i = 0; i < n; i++) {
    if (labels[i]) continue;
    const m = markers[i] as Vector3;
    const j = markers.findIndex((o, k) => k !== i && o.dot(m) < -1 + 1e-6);
    labels[i] = next;
    if (j >= 0) labels[j] = n + 1 - next;
    next++;
  }
  return labels;
}

/**
 * Opposite-pair labels balanced round the corners, as real dice are numbered: opposite faces still sum to n + 1, and
 * the pairs are arranged so the faces meeting at each vertex add up as nearly alike as they can — highs and lows
 * mixed round every corner, never 1 to 5 fanned round one point. A deterministic climb from the plain numbering
 * (every client lays its dice out the same): swap two pairs' values, or turn a pair over, while that evens the
 * corners out.
 */
function balancedLabels(markers: Vector3[], faces: number[][]): number[] {
  const plain = oppositeLabels(markers);
  const n = plain.length;
  const opposite = plain.map((l) => plain.indexOf(n + 1 - l));
  const corners = new Map<number, number[]>();
  faces.forEach((f, fi) => {
    for (const vi of f) corners.set(vi, [...(corners.get(vi) ?? []), fi]);
  });
  const around = [...corners.values()];
  const mean = (around[0]?.length ?? 0) * ((n + 1) / 2);
  // One face of each pair stands for it.
  const pairs = plain.map((_, i) => i).filter((i) => i < (opposite[i] as number));
  const climb = (labels: number[]): { labels: number[]; cost: number } => {
    const cost = () =>
      around.reduce((c, fs) => {
        const d = fs.reduce((t, fi) => t + (labels[fi] as number), 0) - mean;
        return c + d * d;
      }, 0);
    const setPair = (i: number, low: number) => {
      labels[i] = low;
      labels[opposite[i] as number] = n + 1 - low;
    };
    let best = cost();
    for (let improved = true; improved; ) {
      improved = false;
      for (let a = 0; a < pairs.length; a++)
        for (let b = a; b < pairs.length; b++) {
          const i = pairs[a] as number;
          const j = pairs[b] as number;
          const li = labels[i] as number;
          const lj = labels[j] as number;
          // b === a: turn the pair over; otherwise swap the two pairs' values (either way round).
          const tries: [number, number][] =
            a === b
              ? [[n + 1 - li, li]]
              : [
                  [lj, li],
                  [n + 1 - lj, n + 1 - li],
                ];
          for (const [ni, nj] of tries) {
            setPair(i, ni);
            if (a !== b) setPair(j, nj);
            const c = cost();
            if (c < best - 1e-9) {
              best = c;
              improved = true;
              break;
            }
            setPair(i, li);
            if (a !== b) setPair(j, lj);
          }
        }
    }
    return { labels, cost: best };
  };
  // Climbs from the plain numbering and from a fixed series of shuffles of it (a climb can stall short of the best).
  let best = climb([...plain]);
  let seed = 0x9e3779b9;
  const rand = () => {
    seed = (Math.imul(seed ^ (seed >>> 15), 0x2c1b3c6d) + 0x6d2b79f5) >>> 0;
    return seed / 4294967296;
  };
  for (let r = 0; r < 40 && best.cost > 1e-9; r++) {
    const labels = [...plain];
    const lows = pairs.map((_, k) => k + 1);
    for (let k = lows.length - 1; k > 0; k--) {
      const q = Math.floor(rand() * (k + 1));
      [lows[k], lows[q]] = [lows[q] as number, lows[k] as number];
    }
    pairs.forEach((i, k) => {
      const low = lows[k] as number;
      const flip = rand() < 0.5;
      labels[i] = flip ? n + 1 - low : low;
      labels[opposite[i] as number] = flip ? low : n + 1 - low;
    });
    const c = climb(labels);
    if (c.cost < best.cost - 1e-9) best = c;
  }
  return best.labels;
}

function tetrahedron(): Solid {
  const vs = scaled([v(1, 1, 1), v(1, -1, -1), v(-1, 1, -1), v(-1, -1, 1)]);
  // Face i is the one opposite vertex i: when it's down, vertex i is up.
  const faces = orient(vs, [
    [1, 2, 3],
    [0, 2, 3],
    [0, 1, 3],
    [0, 1, 2],
  ]);
  const normals = faces.map((f) => faceNormal(vs, f));
  return {
    kind: "d4",
    vertices: vs,
    faces,
    normals,
    markers: vs.map((p) => p.clone().normalize()),
    labels: [1, 2, 3, 4],
    group: closeGroup([rot(v(1, 1, 1), 120), rot(v(1, 0, 0), 180)]),
  };
}

function cube(): Solid {
  const vs = scaled([
    v(-1, -1, -1),
    v(1, -1, -1),
    v(1, 1, -1),
    v(-1, 1, -1),
    v(-1, -1, 1),
    v(1, -1, 1),
    v(1, 1, 1),
    v(-1, 1, 1),
  ]);
  const faces = orient(vs, [
    [1, 2, 6, 5], // +x
    [0, 4, 7, 3], // −x
    [3, 7, 6, 2], // +y
    [0, 1, 5, 4], // −y
    [4, 5, 6, 7], // +z
    [0, 3, 2, 1], // −z
  ]);
  const normals = faces.map((f) => faceNormal(vs, f));
  return {
    kind: "d6",
    vertices: vs,
    faces,
    normals,
    markers: normals.map((n) => n.clone()),
    labels: [3, 4, 1, 6, 2, 5],
    group: closeGroup([rot(v(1, 0, 0), 90), rot(v(0, 1, 0), 90)]),
  };
}

function octahedron(): Solid {
  const vs = scaled([v(1, 0, 0), v(-1, 0, 0), v(0, 1, 0), v(0, -1, 0), v(0, 0, 1), v(0, 0, -1)]);
  const faces: number[][] = [];
  for (const x of [0, 1]) for (const y of [2, 3]) for (const z of [4, 5]) faces.push([x, y, z]);
  const oriented = orient(vs, faces);
  const normals = oriented.map((f) => faceNormal(vs, f));
  return {
    kind: "d8",
    vertices: vs,
    faces: oriented,
    normals,
    markers: normals.map((n) => n.clone()),
    labels: balancedLabels(normals, oriented),
    group: closeGroup([rot(v(1, 0, 0), 90), rot(v(0, 1, 0), 90)]),
  };
}

function icosahedronVertices(): Vector3[] {
  const out: Vector3[] = [];
  for (const a of [-1, 1])
    for (const b of [-PHI, PHI]) {
      out.push(v(0, a, b));
      out.push(v(a, b, 0));
      out.push(v(b, 0, a));
    }
  return out;
}

/** The icosahedron's faces: every triple of mutually adjacent vertices (edge length 2 before scaling). */
function icosahedronFaces(vs: Vector3[]): number[][] {
  const faces: number[][] = [];
  const edge = (i: number, j: number) => Math.abs((vs[i] as Vector3).distanceTo(vs[j] as Vector3) - 2) < 1e-9;
  for (let i = 0; i < vs.length; i++)
    for (let j = i + 1; j < vs.length; j++)
      for (let k = j + 1; k < vs.length; k++)
        if (edge(i, j) && edge(j, k) && edge(i, k)) faces.push([i, j, k]);
  return faces;
}

// A 5-fold axis (through a vertex) and a 3-fold one (through a face): the whole icosahedral group, order 60.
const ICO_GROUP = () => closeGroup([rot(v(0, 1, PHI), 72), rot(v(1, 1, 1), 120)]);

function icosahedron(): Solid {
  const raw = icosahedronVertices();
  const faces = orient(raw, icosahedronFaces(raw));
  const vs = scaled(raw);
  const normals = faces.map((f) => faceNormal(vs, f));
  return {
    kind: "d20",
    vertices: vs,
    faces,
    normals,
    markers: normals.map((n) => n.clone()),
    labels: balancedLabels(normals, faces),
    group: ICO_GROUP(),
  };
}

function dodecahedron(): Solid {
  // The icosahedron's dual: a vertex at each face's centre; a pentagonal face round each icosahedron vertex.
  const ico = icosahedronVertices();
  const icoFaces = icosahedronFaces(ico);
  const raw = icoFaces.map((f) => {
    const c = new Vector3();
    for (const i of f) c.add(ico[i] as Vector3);
    return c.divideScalar(3);
  });
  const faces: number[][] = ico.map((p, vi) => {
    const around = icoFaces.map((f, fi) => (f.includes(vi) ? fi : -1)).filter((fi) => fi >= 0);
    // Ordered round the vertex's axis.
    const axis = p.clone().normalize();
    const ref = new Vector3()
      .subVectors(raw[around[0] as number] as Vector3, p)
      .projectOnPlane(axis)
      .normalize();
    const side = new Vector3().crossVectors(axis, ref);
    return around
      .map((fi) => {
        const d = new Vector3().subVectors(raw[fi] as Vector3, p).projectOnPlane(axis);
        return { fi, a: Math.atan2(d.dot(side), d.dot(ref)) };
      })
      .sort((x, y) => x.a - y.a)
      .map((x) => x.fi);
  });
  const oriented = orient(raw, faces);
  const vs = scaled(raw);
  const normals = oriented.map((f) => faceNormal(vs, f));
  return {
    kind: "d12",
    vertices: vs,
    faces: oriented,
    normals,
    markers: normals.map((n) => n.clone()),
    labels: balancedLabels(normals, oriented),
    group: ICO_GROUP(),
  };
}

/**
 * The pentagonal trapezohedron: two apexes, two rings of five 36° apart; each kite (apex, ring, other ring, ring) is
 * planar when the apex height is z0 (1 + cos 36°) / (1 − cos 36°).
 */
function trapezohedron(): Solid {
  const z0 = 0.105;
  const c36 = Math.cos(Math.PI / 5);
  const h = (z0 * (1 + c36)) / (1 - c36);
  const raw: Vector3[] = [v(0, h, 0), v(0, -h, 0)];
  for (let k = 0; k < 5; k++) {
    const a = (k * 2 * Math.PI) / 5;
    raw.push(v(Math.cos(a), z0, Math.sin(a)));
  }
  for (let k = 0; k < 5; k++) {
    const a = (k * 2 * Math.PI) / 5 + Math.PI / 5;
    raw.push(v(Math.cos(a), -z0, Math.sin(a)));
  }
  const up = (k: number) => 2 + (k % 5);
  const down = (k: number) => 7 + (k % 5);
  const faces: number[][] = [];
  for (let k = 0; k < 5; k++) faces.push([0, up(k), down(k), up(k + 1)]);
  for (let k = 0; k < 5; k++) faces.push([1, down(k), up(k + 1), down(k + 1)]);
  const oriented = orient(raw, faces);
  const vs = scaled(raw);
  const normals = oriented.map((f) => faceNormal(vs, f));
  // Faces 0–9 (0 reads as 10), opposite faces summing to 9.
  const labels = new Array<number>(10).fill(-1);
  let next = 0;
  for (let i = 0; i < 10; i++) {
    if (labels[i] !== -1) continue;
    const j = normals.findIndex(
      (o, k) => k !== i && labels[k] === -1 && o.dot(normals[i] as Vector3) < -0.99,
    );
    labels[i] = next;
    if (j >= 0) labels[j] = 9 - next;
    next++;
  }
  return {
    kind: "d10",
    vertices: vs,
    faces: oriented,
    normals,
    markers: normals.map((n) => n.clone()),
    labels,
    group: closeGroup([rot(UP, 72), rot(v(Math.cos(Math.PI / 10), 0, Math.sin(Math.PI / 10)), 180)]),
  };
}

const cache = new Map<DieKind, Solid>();

export function solid(kind: DieKind): Solid {
  let s = cache.get(kind);
  if (!s) {
    s =
      kind === "d4"
        ? tetrahedron()
        : kind === "d6"
          ? cube()
          : kind === "d8"
            ? octahedron()
            : kind === "d10"
              ? trapezohedron()
              : kind === "d12"
                ? dodecahedron()
                : icosahedron();
    cache.set(kind, s);
  }
  return s;
}

/** The marker most nearly up for a body at rotation q. */
export function landedMarker(s: Solid, q: Quaternion): number {
  let best = 0;
  let bestDot = Number.NEGATIVE_INFINITY;
  const m = new Vector3();
  for (let i = 0; i < s.markers.length; i++) {
    const d = m
      .copy(s.markers[i] as Vector3)
      .applyQuaternion(q)
      .dot(UP);
    if (d > bestDot) {
      bestDot = d;
      best = i;
    }
  }
  return best;
}

/** The symmetry S taking the wanted marker to the landed one (the mesh is drawn at q_body · S). */
export function remap(s: Solid, landed: number, wanted: number): Quaternion {
  const target = s.markers[landed] as Vector3;
  const from = s.markers[wanted] as Vector3;
  const m = new Vector3();
  for (const g of s.group) if (m.copy(from).applyQuaternion(g).dot(target) > 1 - 1e-6) return g.clone();
  throw new Error(`no symmetry of the ${s.kind} takes marker ${wanted} to ${landed}`);
}

/** The marker showing a value (d10 faces show 0–9, 0 standing for 10). */
export function markerFor(s: Solid, value: number): number {
  const face = s.kind === "d10" ? value % 10 : value;
  const i = s.labels.indexOf(face);
  if (i < 0) throw new Error(`a ${s.kind} has no ${value}`);
  return i;
}
