import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { SRD_521_SPELL_COUNTS, SRD_521_SPELL_TOTAL } from "@gloam/shared";
import { type Spell, SpellSchema } from "@gloam/shared/schemas";

export interface ConditionInfo {
  id: string;
  name: string;
  category: string;
  page: number | null;
  summary: string;
  flags?: Record<string, unknown>;
  srd51?: { summary: string; page: number };
}

export interface LightSourcePreset {
  id: string;
  name: string;
  bright: number;
  dim: number;
  cone?: number;
  durationText: string;
  page: number;
  notes?: string;
}

export interface ContentPack {
  id: "srd-5.2.1";
  spells: Spell[];
  spellById: Map<string, Spell>;
  conditions: ConditionInfo[];
  markers: ConditionInfo[];
  attribution: string;
  lightSources: LightSourcePreset[];
}

const require = createRequire(import.meta.url);

function packDir(id: string): string {
  const pkg = require.resolve("@gloam/content/package.json");
  return join(dirname(pkg), "packs", id);
}

/**
 * Loads the committed SRD pack at startup and asserts its counts (SPEC §11 startup sequence, AC-SPL-01).
 * Runtime never downloads anything: packs are generated by `pnpm content:build` and committed.
 */
export function loadSrdPack(): ContentPack {
  const dir = packDir("srd-5.2.1");
  const raw = JSON.parse(readFileSync(join(dir, "spells.json"), "utf8")) as unknown[];
  const spells = raw.map((s, i) => {
    const r = SpellSchema.safeParse(s);
    if (!r.success) throw new Error(`SRD pack spell #${i} is invalid: ${r.error.issues[0]?.message ?? "?"}`);
    return r.data;
  });
  if (spells.length !== SRD_521_SPELL_TOTAL) {
    throw new Error(`SRD 5.2.1 pack must contain ${SRD_521_SPELL_TOTAL} spells, found ${spells.length}`);
  }
  const perLevel = Array.from({ length: 10 }, (_, l) => spells.filter((s) => s.level === l).length);
  if (perLevel.some((n, l) => n !== SRD_521_SPELL_COUNTS[l])) {
    throw new Error(`SRD 5.2.1 per-level counts ${perLevel.join("/")} ≠ ${SRD_521_SPELL_COUNTS.join("/")}`);
  }
  const cond = JSON.parse(readFileSync(join(dir, "conditions.json"), "utf8")) as {
    attribution: string;
    conditions: ConditionInfo[];
    markers: ConditionInfo[];
  };
  if (cond.conditions.length !== 15) throw new Error("SRD pack must describe all 15 conditions");
  const lightSources = JSON.parse(
    readFileSync(join(dir, "light-sources.json"), "utf8"),
  ) as LightSourcePreset[];
  return {
    id: "srd-5.2.1",
    spells,
    spellById: new Map(spells.map((s) => [s.id, s])),
    conditions: cond.conditions,
    markers: cond.markers,
    attribution: cond.attribution,
    lightSources,
  };
}
