// Generated by tools/extract-icons.mjs from docs/SPEC.md Appendix G — do not edit by hand.
/** Badge colours by category (SPEC Appendix G). */
export const ICON_CATEGORIES = {
  "senses": "#4E7BC4",
  "mind": "#8E5CC8",
  "affliction": "#5E9A4E",
  "body": "#A67C3D",
  "incapacity": "#C8643B",
  "vital": "#B43A36",
  "tactical": "#56657A",
  "boon": "#3F9C78"
} as const;
export type IconCategory = keyof typeof ICON_CATEGORIES;

export interface StatusIconSource {
  id: string;
  name: string;
  category: IconCategory;
  /** A 24 × 24 glyph in currentColor; mask ids are prefixed "gx-". */
  svg: string;
  /** Redrawn at 16 px over the spec's drawing (icons.refined.json, with why). */
  refined?: boolean;
}

export const STATUS_ICONS: readonly StatusIconSource[] = [
  {
    "id": "blinded",
    "name": "Blinded",
    "category": "senses",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><mask id=\"gx-blinded\"><rect width=\"24\" height=\"24\" fill=\"#fff\"/><path d=\"M4.2 19.8L19.8 4.2\" stroke=\"#000\" stroke-width=\"5.4\"/></mask><g mask=\"url(#gx-blinded)\"><path d=\"M2.6 12c2.3-4.2 5.5-6.3 9.4-6.3s7.1 2.1 9.4 6.3c-2.3 4.2-5.5 6.3-9.4 6.3S4.9 16.2 2.6 12z\"/><circle cx=\"12\" cy=\"12\" r=\"2.6\"/></g><path d=\"M4.2 19.8L19.8 4.2\" stroke-width=\"2.2\"/></svg>"
  },
  {
    "id": "charmed",
    "name": "Charmed",
    "category": "mind",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 20.2 C12 20.2 4.2 15.6 4.2 9.9 A4.1 4.1 0 0 1 12 8 A4.1 4.1 0 0 1 19.8 9.9 C19.8 15.6 12 20.2 12 20.2 Z\"/><path d=\"M11.81 12.53 L11.77 12.46 L11.76 12.37 L11.77 12.27 L11.81 12.17 L11.89 12.08 L12 12 L12.13 11.95 L12.29 11.92 L12.45 11.94 L12.63 12 L12.79 12.1 L12.94 12.25 L13.05 12.44 L13.13 12.65 L13.16 12.9 L13.14 13.16 L13.06 13.41 L12.91 13.66 L12.71 13.88 L12.46 14.06 L12.16 14.19 L11.83 14.26 L11.48 14.25 L11.13 14.17 L10.78 14.02 L10.47 13.78 L10.2 13.48 L10 13.12 L9.87 12.71 L9.83 12.27 L9.88 11.81 L10.02 11.36 L10.26 10.94 L10.59 10.57 L11.01 10.27 L11.48 10.05 L12.01 9.93 L12.56 9.92 L13.11 10.03 L13.64 10.25 L14.13 10.59 L14.55 11.02 L14.88 11.54 L15.1 12.14 L15.2 12.77 L15.16 13.43 L14.99 14.08 L14.68 14.69\" stroke-width=\"1.5\"/></svg>"
  },
  {
    "id": "deafened",
    "name": "Deafened",
    "category": "senses",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><mask id=\"gx-deafened\"><rect width=\"24\" height=\"24\" fill=\"#fff\"/><path d=\"M3.8 20.2L20.2 3.8\" stroke=\"#000\" stroke-width=\"5.4\"/></mask><g mask=\"url(#gx-deafened)\"><path d=\"M7 9.6a5.1 5.1 0 0 1 10.2 0c0 2.3-1.2 3.5-2.4 4.6-1 .9-1.4 1.9-1.6 3.1-.3 1.8-1.5 3-3.2 3-1.4 0-2.5-.8-2.9-2\"/><path d=\"M9.8 9.8a2.3 2.3 0 1 1 3.9 1.6c-.7.7-1.5 1.2-1.6 2.3\"/></g><path d=\"M3.8 20.2L20.2 3.8\" stroke-width=\"2.2\"/></svg>"
  },
  {
    "id": "exhaustion",
    "name": "Exhaustion",
    "category": "affliction",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6.5 3.5h11M6.5 20.5h11\"/><path d=\"M8 3.5c0 4.2 4 5.3 4 8.5s-4 4.3-4 8.5M16 3.5c0 4.2-4 5.3-4 8.5s4 4.3 4 8.5\"/><path d=\"M9.6 19.1h4.8L12 16.6z\" fill=\"currentColor\" stroke-width=\"1\"/><path d=\"M10.2 7.4h3.6\" stroke-width=\"1.4\"/></svg>"
  },
  {
    "id": "frightened",
    "name": "Frightened",
    "category": "mind",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 20.6V11a6 6 0 0 1 12 0v9.6l-2-1.6-2 1.6-2-1.6-2 1.6-2-1.6z\"/><circle cx=\"9.9\" cy=\"10.6\" r=\"1.25\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"14.1\" cy=\"10.6\" r=\"1.25\" fill=\"currentColor\" stroke=\"none\"/><ellipse cx=\"12\" cy=\"14.6\" rx=\"1.1\" ry=\"1.5\"/></svg>"
  },
  {
    "id": "grappled",
    "name": "Grappled",
    "category": "body",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.5 13h3.6M17.9 13h3.6\" stroke-width=\"2.6\"/><rect x=\"6.1\" y=\"7.2\" width=\"11.8\" height=\"9.4\" rx=\"3\"/><path d=\"M9.1 7.3v4.4M12 7.3v4.4M14.9 7.3v4.4\"/><path d=\"M6.3 13.4c2 .1 3.6 1.1 4.6 3.1\"/></svg>"
  },
  {
    "id": "incapacitated",
    "name": "Incapacitated",
    "category": "incapacity",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"8.6\"/><path d=\"M5.9 5.9l12.2 12.2\" stroke-width=\"2\"/><path d=\"M13.4 5.9l-4 6.1h3.3l-1.9 6.1\" stroke-width=\"1.6\"/></svg>"
  },
  {
    "id": "invisible",
    "name": "Invisible",
    "category": "senses",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"7\" r=\"3\" stroke-dasharray=\"2 2.1\"/><path d=\"M5.5 20.5v-1.8a6.5 6.5 0 0 1 13 0v1.8\" stroke-dasharray=\"2.2 2.2\"/></svg>"
  },
  {
    "id": "paralyzed",
    "name": "Paralyzed",
    "category": "body",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"5.4\" r=\"2.1\"/><path d=\"M8.6 9.4h6.8M12 9.4v6.3M8.6 9.4v5.4M15.4 9.4v5.4M10.2 15.7v5M13.8 15.7v5\"/><path d=\"M3.2 8.4l1.6 1M2.8 12.4h1.9M3.2 16.4l1.6-1M20.8 8.4l-1.6 1M21.2 12.4h-1.9M20.8 16.4l-1.6-1\" stroke-width=\"1.5\"/></svg>"
  },
  {
    "id": "petrified",
    "name": "Petrified",
    "category": "body",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 9l3-4.6h8L19 9v8.4l-3.2 3.1H8.2L5 17.4z\"/><path d=\"M12.4 4.5l-1.3 4.1 2.2 2.3-1.7 3.4 1.3 3.2-.9 3\" stroke-width=\"1.5\"/><path d=\"M5 9h3.4M15.6 12.5L19 12\" stroke-width=\"1.3\"/></svg>"
  },
  {
    "id": "poisoned",
    "name": "Poisoned",
    "category": "affliction",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M9.4 3.2h5.2M10.4 3.4v5.3L5.7 16.6a3.4 3.4 0 0 0 2.9 5.1h6.8a3.4 3.4 0 0 0 2.9-5.1l-4.7-7.9V3.4\"/><path d=\"M7.5 15.2h9\" stroke-width=\"1.4\"/><circle cx=\"10.3\" cy=\"18.4\" r=\"1.15\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"13.8\" cy=\"17.4\" r=\".8\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"12.6\" cy=\"12.2\" r=\".7\" fill=\"currentColor\" stroke=\"none\"/></svg>"
  },
  {
    "id": "prone",
    "name": "Prone",
    "category": "body",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.8 19.6h18.4\"/><circle cx=\"5.6\" cy=\"14.6\" r=\"2.1\"/><path d=\"M7.9 15.2h9.6l2.8 2.2M11.4 15.2l2-2.7M15.6 15.2l-1.2 2.8\"/></svg>"
  },
  {
    "id": "restrained",
    "name": "Restrained",
    "category": "body",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><rect x=\"2.8\" y=\"8.7\" width=\"11\" height=\"6.2\" rx=\"3.1\" transform=\"rotate(-40 8.3 11.8)\"/><rect x=\"10.2\" y=\"9.1\" width=\"11\" height=\"6.2\" rx=\"3.1\" transform=\"rotate(-40 15.7 12.2)\"/></svg>"
  },
  {
    "id": "stunned",
    "name": "Stunned",
    "category": "incapacity",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12.3 13.2 L12.36 13.26 L12.41 13.35 L12.43 13.45 L12.44 13.56 L12.41 13.68 L12.36 13.8 L12.27 13.91 L12.16 14.02 L12.01 14.1 L11.85 14.15 L11.67 14.17 L11.47 14.16 L11.27 14.11 L11.08 14.01 L10.9 13.88 L10.74 13.7 L10.6 13.49 L10.51 13.25 L10.46 12.98 L10.45 12.7 L10.51 12.41 L10.61 12.12 L10.77 11.85 L10.99 11.6 L11.25 11.39 L11.56 11.23 L11.9 11.11 L12.27 11.06 L12.65 11.08 L13.04 11.16 L13.41 11.32 L13.76 11.54 L14.08 11.83 L14.34 12.19 L14.55 12.59 L14.68 13.03 L14.73 13.5 L14.71 13.99 L14.59 14.47 L14.39 14.93 L14.1 15.37 L13.73 15.75 L13.3 16.07 L12.8 16.31 L12.26 16.47 L11.68 16.53 L11.1 16.49 L10.52 16.35 L9.96 16.1 L9.45 15.75 L8.99 15.32 L8.61 14.79 L8.32 14.21 L8.14 13.56 L8.07 12.89 L8.12 12.2 L8.28 11.52 L8.57 10.87 L8.98 10.27 L9.49 9.74 L10.09 9.3 L10.77 8.97 L11.51 8.75 L12.29 8.67 L13.08 8.72 L13.86 8.91 L14.6 9.24 L15.29 9.7 L15.9 10.28 L16.4 10.96 L16.78 11.73 L17.03 12.56 L17.13 13.44 L17.08 14.33 L16.87 15.22 L16.5 16.06 L15.99 16.84 L15.35 17.52 L14.59 18.09 L13.73 18.53\" stroke-width=\"1.6\"/><path d=\"M5 2.6 L5.57 4.43 L7.4 5 L5.57 5.57 L5 7.4 L4.43 5.57 L2.6 5 L4.43 4.43 Z\" fill=\"currentColor\" stroke-width=\"0.8\"/><path d=\"M19.4 2.6 L19.82 3.98 L21.2 4.4 L19.82 4.82 L19.4 6.2 L18.98 4.82 L17.6 4.4 L18.98 3.98 Z\" fill=\"currentColor\" stroke-width=\"0.8\"/></svg>"
  },
  {
    "id": "unconscious",
    "name": "Unconscious",
    "category": "incapacity",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 14.2h6l-6 6.2h6\" stroke-width=\"2\"/><path d=\"M12 8.6h4.4L12 13h4.4\" stroke-width=\"1.8\"/><path d=\"M17.8 3.6h3.2l-3.2 3.2h3.2\" stroke-width=\"1.5\"/></svg>"
  },
  {
    "id": "bloodied",
    "name": "Bloodied",
    "category": "vital",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 3.2c3.5 4.6 6 8 6 11.3a6 6 0 0 1-12 0c0-3.3 2.5-6.7 6-11.3z\" fill=\"currentColor\" fill-opacity=\".22\"/><path d=\"M9.3 14.2a2.9 2.9 0 0 0 2.2 3\" stroke-width=\"1.5\"/></svg>"
  },
  {
    "id": "concentrating",
    "name": "Concentrating",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"8.6\"/><circle cx=\"12\" cy=\"12\" r=\"5\"/><circle cx=\"12\" cy=\"12\" r=\"1.6\" fill=\"currentColor\" stroke=\"none\"/></svg>"
  },
  {
    "id": "deathsaves",
    "name": "Death saves",
    "category": "vital",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"currentColor\" stroke=\"none\"><path d=\"M11.2 20.2 C11.2 20.2 3.4 15.6 3.4 9.9 A4.1 4.1 0 0 1 11.2 8 L9.8 11.2 L12.2 13 L10.2 16 Z\"/><path d=\"M12.8 8 A4.1 4.1 0 0 1 20.6 9.9 C20.6 15.6 12.8 20.2 12.8 20.2 L11.8 16 L13.8 13 L11.4 11.2 Z\"/></svg>",
    "refined": true
  },
  {
    "id": "stable",
    "name": "Stable",
    "category": "boon",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 20.2 C12 20.2 4.2 15.6 4.2 9.9 A4.1 4.1 0 0 1 12 8 A4.1 4.1 0 0 1 19.8 9.9 C19.8 15.6 12 20.2 12 20.2 Z\"/><path d=\"M12 10.3v5.2M9.4 12.9h5.2\" stroke-width=\"2\"/></svg>"
  },
  {
    "id": "dead",
    "name": "Dead",
    "category": "vital",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6.2 11.2a5.8 5.8 0 0 1 11.6 0v2.6l-1.5 1.1v2.8H7.7v-2.8l-1.5-1.1z\"/><circle cx=\"9.6\" cy=\"11.6\" r=\"1.55\" fill=\"currentColor\" stroke=\"none\"/><circle cx=\"14.4\" cy=\"11.6\" r=\"1.55\" fill=\"currentColor\" stroke=\"none\"/><path d=\"M12 13.9l-.8 1.3h1.6z\" fill=\"currentColor\" stroke-width=\"1\"/><path d=\"M10.3 17.7v2.4M13.7 17.7v2.4M8.4 20.1h7.2\"/></svg>"
  },
  {
    "id": "hidden",
    "name": "Hidden",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4.6 20.6c0-6.1 1.7-11.7 7.4-16 4.4 1.6 7.4 5.6 7.4 10 0 1.1-.3 2.1-.9 3l1.1 3z\"/><path d=\"M12.9 9.4c2 .6 3.4 2.4 3.4 4.4 0 1.2-.6 2.2-1.5 2.9-1.9-.4-3.3-2-3.3-4 0-1.2.5-2.4 1.4-3.3z\" fill=\"currentColor\" fill-opacity=\".35\"/></svg>"
  },
  {
    "id": "surprised",
    "name": "Surprised",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 2.3 L14.3 7.52 L19.82 6.07 L17.17 11.12 L21.75 14.53 L16.14 15.6 L16.34 21.31 L12 17.6 L7.66 21.31 L7.86 15.6 L2.25 14.53 L6.83 11.12 L4.18 6.07 L9.7 7.52 Z\" stroke-width=\"1.5\"/><path d=\"M12 8.7v4.3\" stroke-width=\"2.4\"/><circle cx=\"12\" cy=\"15.5\" r=\"1.25\" fill=\"currentColor\" stroke=\"none\"/></svg>",
    "refined": true
  },
  {
    "id": "dodging",
    "name": "Dodging",
    "category": "boon",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14.2 3.6l6 2.2v5.2c0 4.3-2.6 7.6-6 9.3-3.4-1.7-6-5-6-9.3V5.8z\"/><path d=\"M2.6 8.6h3.2M2 12h3.4M2.6 15.4h3.2\" stroke-width=\"1.5\"/></svg>"
  },
  {
    "id": "disengaged",
    "name": "Disengaged",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"8.6\" cy=\"12\" r=\"5.4\" stroke-dasharray=\"2.4 2\"/><path d=\"M8.6 12h12.2M17.2 8.4l3.6 3.6-3.6 3.6\"/></svg>"
  },
  {
    "id": "dashing",
    "name": "Dashing",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.4 8h5.2M3.8 12h5.2M2.4 16h5.2\" stroke-width=\"1.5\"/><path d=\"M11 5.6l6.4 6.4-6.4 6.4M15.6 5.6l6.4 6.4-6.4 6.4\"/></svg>"
  },
  {
    "id": "inspiration",
    "name": "Heroic Inspiration",
    "category": "boon",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M10.6 7.6 L16.32 10.9 L16.32 17.5 L10.6 20.8 L4.88 17.5 L4.88 10.9 Z\"/><path d=\"M10.6 10.2 L14.2 16.3 L7 16.3 Z\" stroke-width=\"1.4\"/><path d=\"M10.6 7.6v2.6M4.9 17.5l2.1-1.2M16.3 17.5l-2.1-1.2\" stroke-width=\"1.2\"/><path d=\"M19.2 1.6 L19.91 4.09 L22.4 4.8 L19.91 5.51 L19.2 8 L18.49 5.51 L16 4.8 L18.49 4.09 Z\" fill=\"currentColor\" stroke-width=\"0.8\"/></svg>"
  },
  {
    "id": "blessed",
    "name": "Blessed",
    "category": "boon",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"3.8\"/><path d=\"M18.2 12 L21.2 12 M16.38 16.38 L18.51 18.51 M12 18.2 L12 21.2 M7.62 16.38 L5.49 18.51 M5.8 12 L2.8 12 M7.62 7.62 L5.49 5.49 M12 5.8 L12 2.8 M16.38 7.62 L18.51 5.49\"/></svg>"
  },
  {
    "id": "baned",
    "name": "Baned",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3.8 5.4h16.4L12 19.6z\"/><path d=\"M9.2 10.2h5.6\" stroke-width=\"2.2\"/></svg>"
  },
  {
    "id": "hasted",
    "name": "Hasted",
    "category": "boon",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14.6 2.8L7.4 13.2h5.2l-2.2 8 7.4-10.8h-5.3z\" fill=\"currentColor\" fill-opacity=\".22\"/><path d=\"M2.6 9.6h3.4M2 13.4h3.2M2.8 17.2h3\" stroke-width=\"1.5\"/></svg>"
  },
  {
    "id": "slowed",
    "name": "Slowed",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M14.2 11.9 L14.26 11.97 L14.35 12.03 L14.47 12.07 L14.59 12.08 L14.73 12.06 L14.87 12 L15 11.91 L15.12 11.78 L15.22 11.62 L15.29 11.44 L15.32 11.23 L15.31 11.01 L15.25 10.78 L15.15 10.55 L15 10.34 L14.8 10.14 L14.56 9.99 L14.29 9.87 L13.98 9.8 L13.65 9.79 L13.31 9.84 L12.98 9.95 L12.66 10.13 L12.36 10.37 L12.1 10.67 L11.9 11.02 L11.76 11.42 L11.68 11.85 L11.68 12.3 L11.77 12.75 L11.94 13.2 L12.18 13.62 L12.51 14 L12.91 14.32 L13.38 14.58 L13.89 14.75 L14.44 14.84 L15.01 14.83 L15.58 14.72 L16.14 14.5 L16.66 14.18 L17.13 13.77 L17.53 13.28 L17.84 12.7 L18.06 12.08 L18.16 11.41 L18.15 10.71 L18.01 10.02 L17.75 9.35 L17.37 8.72 L16.88 8.16 L16.29 7.68 L15.62 7.3 L14.88 7.05 L14.09 6.92 L13.27 6.93 L12.46 7.08 L11.67 7.38 L10.93 7.81 L10.27 8.38 L9.71 9.06 L9.27 9.83 L8.96 10.69 L8.8 11.6\" stroke-width=\"1.6\"/><path d=\"M3 18.6h16.6\"/><path d=\"M3.4 18.6c.2-2 1.2-3.2 2.8-3.5\"/><path d=\"M4.6 15.4l-1-2.3M6 15.2l.5-2.5\" stroke-width=\"1.3\"/></svg>"
  },
  {
    "id": "burning",
    "name": "Burning",
    "category": "affliction",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M12 21.2a6.2 6.2 0 0 1-6.2-6.2c0-3.6 2.7-5.8 3.9-9.4.4 2.5 1.8 3.7 3 4.3.3-2.5 1.5-4.7 3.5-6.7-.2 3.7 2 5.8 2 9.8a6.2 6.2 0 0 1-6.2 8.2z\"/><path d=\"M12 21.2a2.8 2.8 0 0 1-2.8-2.8c0-1.9 1.4-2.8 2.2-4.2.7 1.4 2.4 2.1 3.2 3.6.3.6.2 1.2-.1 1.7a2.8 2.8 0 0 1-2.5 1.7z\" fill=\"currentColor\" fill-opacity=\".35\"/></svg>"
  },
  {
    "id": "flying",
    "name": "Flying",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M2.8 17.4C6.9 10.3 12.9 6.2 21.2 4.4c-.3 2.7-1.2 4.9-2.7 6.6l-3.7.2c-.9 1.6-2.2 2.9-3.8 3.6l-3.6.1c-1.2 1.6-2.7 2.5-4.6 2.5z\"/><path d=\"M14.8 11.2c1.4-1.5 2.7-3 3.9-4.6M11 14.8c1.9-1.4 3.6-3 5.1-4.8\" stroke-width=\"1.3\"/></svg>"
  },
  {
    "id": "readied",
    "name": "Readied",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"6.6\"/><path d=\"M12 2.6v4.2M12 17.2v4.2M2.6 12h4.2M17.2 12h4.2\"/><circle cx=\"12\" cy=\"12\" r=\"1.3\" fill=\"currentColor\" stroke=\"none\"/></svg>"
  },
  {
    "id": "custom",
    "name": "Custom marker",
    "category": "tactical",
    "svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.75\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5.4 3.6h13.2v16.8L12 16.6l-6.6 3.8z\"/></svg>"
  }
];
