#!/usr/bin/env node
// Extracts the condition and status icons from docs/SPEC.md Appendix G (SPEC §30) into
// packages/shared/src/icons.generated.ts — the one source for the React components and the WebGL atlas.
// Usage: node tools/extract-icons.mjs [--check]   (--check: fail if the generated file is out of date)
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ROOT } from "./features-lib.mjs";

const spec = readFileSync(join(ROOT, "docs", "SPEC.md"), "utf8");
const start = spec.indexOf("## Appendix G");
const end = spec.indexOf("## Appendix H", start);
if (start < 0 || end < 0) throw new Error("Appendix G not found");
const appendix = spec.slice(start, end);

// Badge categories: | Category | `#hex` | Icons |
const categories = {};
for (const m of appendix.matchAll(/^\| (\w[\w ]*?) \| `(#[0-9A-Fa-f]{6})` \| /gm))
  categories[m[1].toLowerCase()] = m[2].toUpperCase();

const icons = [];
for (const m of appendix.matchAll(/<!-- (\w+) · ([^·]+?) · (\w+) -->\s*\n(<svg[^\n]*<\/svg>)/g)) {
  const [, id, name, category, svg] = m;
  if (!categories[category]) throw new Error(`unknown category ${category} for ${id}`);
  icons.push({ id, name: name.trim(), category, svg });
}
if (icons.length < 30) throw new Error(`only ${icons.length} icons found`);

// Refinements at 16 px (SPEC §30.1 "refine proportions at 16 px, keep the concepts"): hand-drawn over the spec's
// drawing for the listed ids, each with its reason. An id the spec doesn't have is an error.
const refined = JSON.parse(
  readFileSync(join(ROOT, "packages", "shared", "src", "icons.refined.json"), "utf8"),
);
for (const [id, r] of Object.entries(refined)) {
  if (id.startsWith("_")) continue;
  const icon = icons.find((i) => i.id === id);
  if (!icon) throw new Error(`icons.refined.json: no icon "${id}" in Appendix G`);
  if (!r.why || !/^<svg[^\n]*<\/svg>$/.test(r.svg))
    throw new Error(`icons.refined.json: "${id}" needs why and one-line svg`);
  icon.svg = r.svg;
  icon.refined = true;
}

const out = `// Generated by tools/extract-icons.mjs from docs/SPEC.md Appendix G — do not edit by hand.
/** Badge colours by category (SPEC Appendix G). */
export const ICON_CATEGORIES = ${JSON.stringify(categories, null, 2)} as const;
export type IconCategory = keyof typeof ICON_CATEGORIES;

export interface StatusIconSource {
  id: string;
  name: string;
  category: IconCategory;
  /** A 24 × 24 glyph in currentColor; mask ids are prefixed "gx-". */
  svg: string;
  /** Redrawn at 16 px over the spec's drawing (icons.refined.json, with why). */
  refined?: boolean;
}

export const STATUS_ICONS: readonly StatusIconSource[] = ${JSON.stringify(icons, null, 2)};
`;
const target = join(ROOT, "packages", "shared", "src", "icons.generated.ts");
if (process.argv.includes("--check")) {
  const cur = readFileSync(target, "utf8");
  if (cur !== out) {
    console.error("icons.generated.ts is out of date: run node tools/extract-icons.mjs");
    process.exit(1);
  }
  console.log(`icons: ${icons.length} up to date`);
} else {
  writeFileSync(target, out);
  console.log(`icons: ${icons.length} written (${Object.keys(categories).length} categories)`);
}
